/**
 * The emoji pool the reaction picker offers. Plain data, no dependency: each entry is
 * [emoji, lowercase English name], the name powering the picker's search box. Groups
 * render as labeled sections; the search flattens them.
 */
export type Emoji = [emoji: string, name: string];

export interface EmojiGroup {
  name: string;
  emojis: Emoji[];
}

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    name: "Smileys & People",
    emojis: [
      ["😀", "grinning"],
      ["😃", "smiley"],
      ["😄", "smile"],
      ["😁", "beaming"],
      ["😆", "laughing"],
      ["😅", "sweat smile"],
      ["🤣", "rofl"],
      ["😂", "joy"],
      ["🙂", "slight smile"],
      ["😉", "wink"],
      ["😊", "blush"],
      ["😇", "halo"],
      ["🥰", "hearts face"],
      ["😍", "heart eyes"],
      ["😘", "kiss"],
      ["😋", "yum"],
      ["😜", "zany"],
      ["🤪", "crazy"],
      ["🤨", "raised eyebrow"],
      ["🧐", "monocle"],
      ["🤓", "nerd"],
      ["😎", "cool"],
      ["🥳", "party"],
      ["😏", "smirk"],
      ["😒", "unamused"],
      ["😞", "disappointed"],
      ["😔", "pensive"],
      ["🙁", "frown"],
      ["🥺", "pleading"],
      ["😢", "cry"],
      ["😭", "sob"],
      ["😤", "triumph"],
      ["😠", "angry"],
      ["😡", "rage"],
      ["🤯", "mind blown"],
      ["😳", "flushed"],
      ["🥵", "hot"],
      ["🥶", "cold"],
      ["😱", "scream"],
      ["😨", "fearful"],
      ["🤗", "hug"],
      ["🤔", "thinking"],
      ["🤫", "shush"],
      ["🤭", "giggle"],
      ["😐", "neutral"],
      ["😬", "grimace"],
      ["🙄", "eye roll"],
      ["😴", "sleeping"],
      ["🤤", "drooling"],
      ["😮", "wow"],
      ["😲", "astonished"],
      ["🥱", "yawn"],
      ["🤒", "sick"],
      ["🤕", "bandage"],
      ["🤠", "cowboy"],
      ["🥸", "disguise"],
      ["🤡", "clown"],
      ["👻", "ghost"],
      ["💀", "skull"],
      ["👽", "alien"],
      ["🤖", "robot"],
      ["💩", "pile of poo"],
      ["🦸", "superhero"],
      ["🦹", "supervillain"],
    ],
  },
  {
    name: "Gestures",
    emojis: [
      ["👍", "thumbs up"],
      ["👎", "thumbs down"],
      ["👊", "fist bump"],
      ["✊", "raised fist"],
      ["🤛", "left fist"],
      ["🤜", "right fist"],
      ["✌️", "peace"],
      ["🤞", "crossed fingers"],
      ["🤟", "love you"],
      ["🤘", "rock on"],
      ["🤙", "call me"],
      ["👌", "ok"],
      ["🤌", "pinched fingers"],
      ["👈", "point left"],
      ["👉", "point right"],
      ["👆", "point up"],
      ["👇", "point down"],
      ["☝️", "index up"],
      ["✋", "raised hand"],
      ["🖐", "high five"],
      ["🖖", "spock"],
      ["👋", "wave"],
      ["🤝", "handshake"],
      ["🙏", "please"],
      ["💪", "flexed biceps"],
      ["🫡", "salute"],
      ["🤲", "palms up"],
      ["👏", "clap"],
      ["🙌", "raising hands"],
      ["🫶", "heart hands"],
      ["✍️", "writing"],
    ],
  },
  {
    name: "Hearts & Symbols",
    emojis: [
      ["❤️", "red heart"],
      ["🧡", "orange heart"],
      ["💛", "yellow heart"],
      ["💚", "green heart"],
      ["💙", "blue heart"],
      ["💜", "purple heart"],
      ["🖤", "black heart"],
      ["🤍", "white heart"],
      ["🤎", "brown heart"],
      ["💔", "broken heart"],
      ["❣️", "heart exclamation"],
      ["💕", "two hearts"],
      ["💞", "revolving hearts"],
      ["💓", "beating heart"],
      ["💗", "growing heart"],
      ["💖", "sparkling heart"],
      ["💘", "heart arrow"],
      ["💝", "heart ribbon"],
      ["✨", "sparkles"],
      ["⭐", "star"],
      ["🌟", "glowing star"],
      ["💫", "dizzy"],
      ["⚡", "lightning"],
      ["🔥", "fire"],
      ["💯", "hundred points"],
      ["✅", "check"],
      ["❌", "cross"],
      ["❓", "question"],
      ["❗", "exclamation"],
      ["🔔", "bell"],
      ["🎯", "dart"],
      ["♻️", "recycle"],
      ["⚠️", "warning"],
      ["🚫", "prohibited"],
      ["🏁", "checkered flag"],
      ["🚩", "triangle flag"],
      ["🎉", "party popper"],
      ["🎊", "confetti"],
      ["🎈", "balloon"],
      ["🎁", "gift"],
    ],
  },
  {
    name: "Animals & Nature",
    emojis: [
      ["🐶", "dog"],
      ["🐱", "cat"],
      ["🐭", "mouse"],
      ["🐹", "hamster"],
      ["🐰", "rabbit"],
      ["🦊", "fox"],
      ["🐻", "bear"],
      ["🐼", "panda"],
      ["🐨", "koala"],
      ["🐯", "tiger"],
      ["🦁", "lion"],
      ["🐮", "cow"],
      ["🐷", "pig"],
      ["🐸", "frog"],
      ["🐵", "monkey"],
      ["🐔", "chicken"],
      ["🐧", "penguin"],
      ["🐦", "bird"],
      ["🦆", "duck"],
      ["🦅", "eagle"],
      ["🦉", "owl"],
      ["🦇", "bat"],
      ["🐺", "wolf"],
      ["🐴", "horse"],
      ["🦄", "unicorn"],
      ["🐝", "bee"],
      ["🦋", "butterfly"],
      ["🐞", "ladybug"],
      ["🐢", "turtle"],
      ["🐍", "snake"],
      ["🐙", "octopus"],
      ["🦀", "crab"],
      ["🐠", "fish"],
      ["🐬", "dolphin"],
      ["🐳", "whale"],
      ["🦈", "shark"],
      ["🌵", "cactus"],
      ["🌲", "evergreen"],
      ["🌳", "tree"],
      ["🌴", "palm tree"],
      ["🌱", "seedling"],
      ["🌿", "herb"],
      ["🍀", "clover"],
      ["🌸", "cherry blossom"],
      ["🌷", "tulip"],
      ["🌹", "rose"],
      ["🌻", "sunflower"],
      ["💐", "bouquet"],
      ["🌞", "sun"],
      ["🌝", "moon face"],
      ["🌈", "rainbow"],
      ["☁️", "cloud"],
      ["🌧️", "rain"],
      ["❄️", "snowflake"],
      ["🌊", "wave"],
    ],
  },
  {
    name: "Food & Drink",
    emojis: [
      ["🍏", "green apple"],
      ["🍎", "apple"],
      ["🍐", "pear"],
      ["🍊", "orange"],
      ["🍋", "lemon"],
      ["🍌", "banana"],
      ["🍉", "watermelon"],
      ["🍇", "grapes"],
      ["🍓", "strawberry"],
      ["🫐", "blueberries"],
      ["🍒", "cherries"],
      ["🍑", "peach"],
      ["🥭", "mango"],
      ["🍍", "pineapple"],
      ["🥥", "coconut"],
      ["🥝", "kiwi"],
      ["🍅", "tomato"],
      ["🥑", "avocado"],
      ["🥦", "broccoli"],
      ["🥕", "carrot"],
      ["🌽", "corn"],
      ["🌶️", "hot pepper"],
      ["🥒", "cucumber"],
      ["🍄", "mushroom"],
      ["🥜", "peanuts"],
      ["🍞", "bread"],
      ["🥐", "croissant"],
      ["🥨", "pretzel"],
      ["🧀", "cheese"],
      ["🥚", "egg"],
      ["🍳", "fried egg"],
      ["🥞", "pancakes"],
      ["🧇", "waffle"],
      ["🥓", "bacon"],
      ["🍔", "burger"],
      ["🍟", "fries"],
      ["🍕", "pizza"],
      ["🌭", "hot dog"],
      ["🥪", "sandwich"],
      ["🌮", "taco"],
      ["🌯", "burrito"],
      ["🥗", "salad"],
      ["🍝", "spaghetti"],
      ["🍜", "noodles"],
      ["🍣", "sushi"],
      ["🍱", "bento"],
      ["🍤", "shrimp"],
      ["🍚", "rice"],
      ["🍦", "ice cream"],
      ["🍰", "cake"],
      ["🎂", "birthday cake"],
      ["🍫", "chocolate"],
      ["🍬", "candy"],
      ["🍭", "lollipop"],
      ["🍩", "doughnut"],
      ["🍪", "cookie"],
      ["☕", "coffee"],
      ["🍵", "tea"],
      ["🧋", "bubble tea"],
      ["🥤", "soft drink"],
      ["🍺", "beer"],
      ["🥂", "champagne"],
      ["🍷", "wine"],
      ["🍸", "cocktail"],
    ],
  },
  {
    name: "Activities",
    emojis: [
      ["⚽", "soccer"],
      ["🏀", "basketball"],
      ["🏈", "football"],
      ["⚾", "baseball"],
      ["🎾", "tennis"],
      ["🏐", "volleyball"],
      ["🎱", "pool"],
      ["🏓", "ping pong"],
      ["🏸", "badminton"],
      ["🥊", "boxing"],
      ["⛳", "golf"],
      ["🏹", "archery"],
      ["🎣", "fishing"],
      ["🎿", "ski"],
      ["🏂", "snowboard"],
      ["🏄", "surfing"],
      ["🏊", "swimming"],
      ["🚴", "cycling"],
      ["🧘", "yoga"],
      ["🎮", "game controller"],
      ["🎲", "dice"],
      ["♟", "chess"],
      ["🧩", "puzzle"],
      ["🎨", "art"],
      ["🎬", "clapper"],
      ["🎤", "microphone"],
      ["🎧", "headphones"],
      ["🎼", "music score"],
      ["🎹", "piano"],
      ["🥁", "drum"],
      ["🎸", "guitar"],
      ["🎺", "trumpet"],
      ["🎻", "violin"],
      ["🏆", "trophy"],
      ["🥇", "gold medal"],
      ["🥈", "silver medal"],
      ["🥉", "bronze medal"],
    ],
  },
  {
    name: "Travel & Places",
    emojis: [
      ["🚗", "car"],
      ["🚕", "taxi"],
      ["🚙", "suv"],
      ["🚌", "bus"],
      ["🏎", "race car"],
      ["🚓", "police car"],
      ["🚑", "ambulance"],
      ["🚒", "fire engine"],
      ["🚚", "truck"],
      ["🚜", "tractor"],
      ["🛵", "scooter"],
      ["🚲", "bicycle"],
      ["✈️", "airplane"],
      ["🚀", "rocket"],
      ["🚁", "helicopter"],
      ["⛵", "sailboat"],
      ["🚤", "speedboat"],
      ["🛳", "ship"],
      ["🗽", "statue of liberty"],
      ["🗼", "tokyo tower"],
      ["🏰", "castle"],
      ["🏯", "japanese castle"],
      ["🎡", "ferris wheel"],
      ["🎢", "roller coaster"],
      ["⛰", "mountain"],
      ["🌋", "volcano"],
      ["🏝", "island"],
      ["🏖", "beach"],
      ["🌅", "sunrise"],
      ["🌇", "sunset"],
      ["🌃", "night"],
      ["🏙", "cityscape"],
      ["🌉", "bridge"],
      ["🗺", "map"],
      ["🧭", "compass"],
    ],
  },
  {
    name: "Objects",
    emojis: [
      ["⌚", "watch"],
      ["📱", "phone"],
      ["💻", "laptop"],
      ["⌨️", "keyboard"],
      ["🖥", "desktop"],
      ["🖨", "printer"],
      ["🖱", "computer mouse"],
      ["📷", "camera"],
      ["📹", "video camera"],
      ["📺", "television"],
      ["📞", "telephone"],
      ["⏰", "alarm clock"],
      ["⏳", "hourglass"],
      ["📡", "satellite antenna"],
      ["🔋", "battery"],
      ["🔌", "plug"],
      ["💡", "light bulb"],
      ["🔦", "flashlight"],
      ["📚", "books"],
      ["📖", "open book"],
      ["🔖", "bookmark"],
      ["🔗", "link"],
      ["📌", "pushpin"],
      ["📍", "round pushpin"],
      ["✂️", "scissors"],
      ["🖊", "pen"],
      ["📝", "memo"],
      ["✏️", "pencil"],
      ["🔍", "magnifier"],
      ["🔒", "locked"],
      ["🔓", "unlocked"],
      ["🗝", "key"],
      ["🔨", "hammer"],
      ["🛠", "tools"],
      ["⚙️", "gear"],
      ["🧲", "magnet"],
      ["💰", "money bag"],
      ["💳", "credit card"],
      ["💎", "gem"],
      ["⚖️", "scales"],
      ["🧪", "test tube"],
      ["🔬", "microscope"],
      ["🔭", "telescope"],
      ["📦", "package"],
      ["✉️", "envelope"],
      ["📮", "mailbox"],
      ["🗓", "calendar"],
      ["📅", "calendar date"],
      ["🗑", "trash"],
      ["🪄", "magic wand"],
    ],
  },
];

/** All emojis in one flat list, for the search view. */
export const ALL_EMOJIS: Emoji[] = EMOJI_GROUPS.flatMap((group) => group.emojis);
